name: Build Image and Test with Snyk

on:
  workflow_dispatch:
  workflow_call:

env:
  IMAGE_NAME: troysnyk/nodejs-goof
  IMAGE_TAG: linux

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Extract metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.IMAGE_NAME }}
            tags: linux

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            provenance: mode=max
            tags: ${{ steps.meta.outputs.tags }}

        - uses: snyk/actions/setup@master
        - name: Snyk Container Monitor 
          run: snyk container monitor ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --file=Dockerfile
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}